name: e2e Part

on:
  workflow_call:
    inputs:
      FROM:
        type: string
        required: false
      COUNT:
        type: string
        required: false
    secrets:
      SUBSCAN_PRO_API_KEY:
        required: true
      ZYTE_USER:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Server Dependencies
        working-directory: server
        run: npm ci

      - name: Run e2e tests
        working-directory: server
        run: npm run e2e-tests:data
        env:
          SUBSCAN_API_KEY: ${{ secrets.SUBSCAN_PRO_API_KEY }}
          ZYTE_USER: ${{ secrets.ZYTE_USER }}
          LOG_LEVEL: warn
          FROM: ${{ inputs.FROM }}
          COUNT: ${{ inputs.COUNT }}
