name: e2e Tests

on:
  workflow_dispatch:

jobs:
  # 1️⃣ First job
  e2e-tests-events:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Server Dependencies
        working-directory: server
        run: npm install

      - name: Run e2e Tests jest
        working-directory: server
        run: npm run e2e-tests:jest
        env:
          SUBSCAN_API_KEY: ${{ secrets.SUBSCAN_PRO_API_KEY }}
          ZYTE_USER: ${{ secrets.ZYTE_USER }}

      - name: Run e2e Tests data
        working-directory: server
        run: npm run e2e-tests:data
        env:
          LOG_LEVEL: warn
          SUBSCAN_API_KEY: ${{ secrets.SUBSCAN_PRO_API_KEY }}
          ZYTE_USER: ${{ secrets.ZYTE_USER }}

  # 2️⃣ Second job (runs AFTER e2e-tests-events)
  e2e-tests-data-part-1:
    needs: e2e-tests-events      
    uses: ./.github/workflows/e2e-part.yml
    with:
      count: "15"
    secrets: inherit

  # 3️⃣ Third job (runs AFTER part-1)
  e2e-tests-data-part-2:
    needs: e2e-tests-data-part-1  
    uses: ./.github/workflows/e2e-part.yml
    with:
      from: "15"
    secrets: inherit
